export const coordinatorsData = {
  "Web Development": [
    {
      id: 1,
      name: "Shivam Tiwari",
      position: "Lead Web Developer",
      bio: "Passionate about creating seamless web experiences.",
      photo: "/Shivam Tiwari.jpeg",
      socials: {
        linkedin: "https://linkedin.com/in/alicejohnson",
        github: "https://github.com/alicejohnson",
        email: "mailto:shivam.tiwari@example.com",
      },
      branch: "CSE (IoT)",
      year: "3rd Year",
    },
    {
      id: 2,
      name: "Anshika Jaiswal",
      position: "Senior Web Developer",
      bio: "Specialized in frontend technologies and responsive design.",
      photo: "/images/john.jpg",
      socials: {
        linkedin: "https://linkedin.com/in/johndoe",
        github: "https://github.com/johndoe",
        email: "mailto:anshika.jaiswal@example.com",
      },
      branch: "CSE",
      year: "4th Year",
    },
    {
      id: 17,
      name: "Aryan kumar",
      position: "Event Coordinator",
      bio: "Managing and organizing events with precision and creativity.",
      photo: "/aryan kumar.jpg",
      socials: {
        linkedin: "https://linkedin.com/in/charlottemoore",
        github: "https://github.com/charlottemoore",
        email: "mailto:kashish.patel@example.com",
      },
      branch: "CSE (IoT)",
      year: "3rd Year",
    },
  ],
  Hardware: [
    {
      id: 10,
      name: "Chetan Chauhan",
      position: "Embedded Systems Engineer",
      bio: "Passionate about building efficient hardware solutions.",
      photo: "/chetan chauhan.jpg",
      socials: {
        linkedin: "https://linkedin.com/in/ethanjames",
        github: "https://github.com/ethanjames",
        email: "mailto:chetan.chauhan@example.com",
      },
      branch: "ECE",
      year: "3rd Year",
    },
    {
      id: 9,
      name: "Aditya Shekhar Das",
      position: "Lead Hardware Engineer",
      bio: "Expert in circuit design and embedded systems.",
      photo: "/aditya shekhar das.jpeg",
      socials: {
        linkedin: "https://linkedin.com/in/alicecooper",
        github: "https://github.com/alicecooper",
        email: "mailto:aditya.das@example.com",
      },
      branch: "ECE",
      year: "4th Year",
    },
    {
      id: 25,
      name: "Gaurav Gupta",
      position: "Embedded Systems Engineer",
      bio: "Passionate about building efficient hardware solutions.",
      photo: "/gaurav gupta.jpeg",
      socials: {
        linkedin: "https://linkedin.com/in/ethanjames",
        github: "https://github.com/ethanjames",
        email: "mailto:gaurav.gupta@example.com",
      },
      branch: "ECE",
      year: "3rd Year",
    },
    {
      id: 11,
      name: "Ankur Anand",
      position: "Hardware Specialist",
      bio: "Skilled in PCB design and testing.",
      photo: "/ankur anand.jpeg",
      socials: {
        linkedin: "https://linkedin.com/in/isabellagreen",
        github: "https://github.com/isabellagreen",
        email: "mailto:ankur.anand@example.com",
      },
      branch: "ECE",
      year: "4th Year",
    },
    {
      id: 12,
      name: "Pratyush Sachan",
      position: "IoT Hardware Engineer",
      bio: "Building smart devices for the future.",
      photo: "/pratyush sachan.jpeg",
      socials: {
        linkedin:
          "https://www.linkedin.com/in/pratyush-sachan-76072328a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github:
          " https://search.app?link=https%3A%2F%2Fgithub.com%2Fprojects&utm_campaign=aga&utm_source=agsadl1%2Csh%2Fx%2Fgs%2Fm2%2F4",
        email: "mailto: sachanpratyush334@gmail.com",
      },
      branch: "ECE",
      year: "3rd Year",
    },
  ],
  "App Development": [
    {
      id: 25,
      name: "Shashank Kumar Acharya",
      position: "App Developer",
      bio: "passionate about app development in flutter",
      photo: "/shashank kumar acharya.png",
      socials: {
        linkedin: "https://linkedin.com/in/sophialee",
        github: "https://github.com/sophialee",
        email: "mailto:sophia.lee@example.com",
      },
      branch: "CSE IoT",
      year: "2nd Year",
    },
  ],
  AIML: [
    {
      id: 25,
      name: "Aditya Mishra",
      position: "AIML coordinator",
      bio: "Building ML model for projects at Signodes",
      photo: "/aditya mishra.jpg",
      socials: {
        linkedin: "https://linkedin.com/in/sophialee",
        github: "https://github.com/sophialee",
        email: "mailto:sophia.lee@example.com",
      },
      branch: "CSE IoT",
      year: "2nd Year",
    },
    {
      id: 25,
      name: "Raushan Kumar",
      position: "AIML coordinator",
      bio: "passionate about trending AI uses and ML models",
      photo: "/raushan kumar.jpg",
      socials: {
        linkedin: "https://linkedin.com/in/sophialee",
        github: "https://github.com/sophialee",
        email: "mailto:sophia.lee@example.com",
      },
      branch: "CSE AIML",
      year: "3rd Year",
    },
  ],

  "Technical Documentation": [
    {
      id: 13,
      name: "Kumal Kr Dubey",
      position: "Technical Documentation And Product Designing",
      bio: "Passionate about writing clear and concise technical documentation.",
      photo: "/kunal kr dubey.jpg",
      socials: {
        linkedin: "https://linkedin.com/in/oliviataylor",
        github: "https://github.com/oliviataylor",
        email: "mailto:olivia.taylor@example.com",
      },
      branch: "CSE-IoT",
      year: "2nd Year",
    },
  ],
  "Content Creator": [
    {
      id: 22,
      name: "Shlok Singh",
      position: "Content creator and video editor",
      bio: "Creating engaging content to boost online presence.",
      photo: "/shlok singh.jpg",
      socials: {
        linkedin: "https://www.linkedin.com/in/shlok-singh-5182b0203?utm_",
        github: "https://github.com/Dr-doom0808",
        email: "mailto:shloksingh528128@gmail.com ",
      },
      branch: "CSE-IoT",
      year: "2nd Year",
    },
  ],
  "Event Management": [
    {
      id: 17,
      name: "Kashish Patel",
      position: "Event Coordinator",
      bio: "Managing and organizing events with precision and creativity.",
      photo: "/kashish patel.jpg",
      socials: {
        linkedin: "https://linkedin.com/in/charlottemoore",
        github: "https://github.com/charlottemoore",
        email: "mailto:kashish.patel@example.com",
      },
      branch: "CSE (IoT)",
      year: "3rd Year",
    },
    {
      id: 22,
      name: "Manas Sharma",
      position: "Conteneditort creator and video ",
      bio: "Event Manager.",
      photo: "/manas sharma.jpg",
      socials: {
        linkedin: "https://www.linkedin.com/in/shlok-singh-5182b0203?utm_",
        github: "https://github.com/Dr-doom0808",
        email: "mailto:shloksingh528128@gmail.com ",
      },
      branch: "CSE-IoT",
      year: "2nd Year",
    },
  ],
  "Social Media": [
    {
      id: 17,
      name: "Arpita Jaiswal",
      position: "Event Coordinator",
      bio: "Managing and organizing events with precision and creativity.",
      photo: "/arpita jaiswal.jpg",
      socials: {
        linkedin: "https://linkedin.com/in/charlottemoore",
        github: "https://github.com/charlottemoore",
        email: "mailto:kashish.patel@example.com",
      },
      branch: "CSE (IoT)",
      year: "3rd Year",
    },
    {
      id: 17,
      name: "Vaishnavi Singh",
      position: "Event Coordinator",
      bio: "Managing and organizing events with precision and creativity.",
      photo: "/vaishnavi singh.jpg",
      socials: {
        linkedin: "https://linkedin.com/in/charlottemoore",
        github: "https://github.com/charlottemoore",
        email: "mailto:kashish.patel@example.com",
      },
      branch: "CSE (IoT)",
      year: "2nd Year",
    },
  ],
};